[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.163.3"

# Les pages du CMS ne doivent pas être mises en cache agressivement
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
